# Knowledge Graph Domain - Data Mesh Architecture Metadata
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: knowledge-graph
  description: 知识图谱域 - Data Mesh 架构元数据与概念关系
  tags:
    - domain
    - metadata
    - knowledge-graph
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: platform-team

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dp-domain-knowledge-graph
  title: Data Product - Domain Knowledge Graph
  description: |
    Data Mesh 领域知识图谱数据产品
    
    提供 Data Mesh 架构中的概念、领域、数据产品、平台组件和团队之间的关系图谱。
    这是一个元数据产品，帮助理解和导航整个 Data Mesh 生态系统。
    
    **数据内容**:
    - Data Mesh 核心概念 (Domain Ownership, Data as Product, Self-Serve Platform, Federated Governance)
    - 业务领域定义与关系
    - 数据产品清单与依赖
    - 平台组件交互关系
    - 团队所有权映射
    - 治理概念与实施
    
    **访问方式**:
    - Neo4j Browser: http://localhost:7474
    - Bolt Protocol: bolt://localhost:7687
    - HTTP API: http://localhost:7474/db/neo4j/tx
    
    **查询示例**:
    ```cypher
    // 查看所有数据产品及其依赖
    MATCH (d:Domain)-[:OWNS]->(dp:DataProduct)-[:CONSUMES_FROM]->(source:Domain)
    RETURN d.name_cn as owner, dp.name_cn as product, source.name_cn as source
    
    // 查看团队职责范围
    MATCH (t:Team)-[:OWNS|MAINTAINS]->(entity)
    RETURN t.name_cn as team, labels(entity)[0] as type, entity.name as name
    ```
  tags:
    - data-product
    - knowledge-graph
    - metadata
    - neo4j
  links:
    - url: http://localhost:7474
      title: Neo4j Browser
      icon: dashboard
    - url: http://localhost:7474/browser/?cmd=play&arg=start
      title: Quick Start Guide
  annotations:
    backstage.io/techdocs-ref: dir:.
    graph.neo4j/uri: neo4j://localhost:7687
spec:
  type: data-product
  lifecycle: production
  owner: platform-team
  domain: knowledge-graph
  system: datamesh-platform
  providesApis:
    - neo4j-bolt-api
    - neo4j-http-api
  dependsOn:
    - component:openmetadata-catalog
    - component:backstage
  
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: neo4j-bolt-api
  description: Neo4j Bolt Protocol API - 图数据库查询协议
  tags:
    - neo4j
    - graph-db
spec:
  type: graphql
  lifecycle: production
  owner: platform-team
  system: datamesh-platform
  definition: |
    # Neo4j Bolt Protocol
    Connection: bolt://localhost:7687
    Authentication: neo4j/datamesh123
    
    # Example Query
    MATCH (n:DataProduct) RETURN n

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: neo4j-http-api
  description: Neo4j HTTP Transactional API - REST 风格的图查询接口
  tags:
    - neo4j
    - rest-api
spec:
  type: openapi
  lifecycle: production
  owner: platform-team
  system: datamesh-platform
  definition: |
    openapi: 3.0.0
    info:
      title: Neo4j HTTP API
      version: 5.15.0
    servers:
      - url: http://localhost:7474/db/neo4j/tx
    paths:
      /commit:
        post:
          summary: Execute Cypher statements
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    statements:
                      type: array
                      items:
                        type: object
                        properties:
                          statement:
                            type: string
                            example: "MATCH (n) RETURN n LIMIT 10"

